function __ls_icon -a name full
    set -l icon "󰈔"
    set -l lower (string lower -- "$name")

    if test -d "$full"
        set icon ""
        switch $lower
            case .git;                 set icon ""
            case node_modules;         set icon ""
            case .config config configs; set icon ""
            case desktop;              set icon ""
            case documents docs documentation; set icon "󰈙"
            case downloads;            set icon ""
            case music;                set icon "󰝚"
            case pictures images image img; set icon ""
            case videos;               set icon ""
            case public;               set icon ""
            case templates;            set icon ""
            case 'my projects' projects developer dev; set icon "󰲋"
            case src source sources;   set icon "󰉿"
            case scripts script bin;   set icon ""
            case dist build out target; set icon "󰏖"
            case test tests __tests__ spec specs; set icon "󰙨"
            case .venv venv;           set icon ""
            case .github;              set icon ""
        end
    else
        switch $lower
            case .gitignore .gitattributes .gitmodules; set icon ""
            case package.json package-lock.json npm-shrinkwrap.json; set icon ""
            case pnpm-lock.yaml pnpm-workspace.yaml; set icon ""
            case yarn.lock;            set icon ""
            case bun.lockb bunfig.toml; set icon ""
            case deno.json deno.jsonc; set icon ""
            case dockerfile docker-compose.yml docker-compose.yaml compose.yml compose.yaml; set icon ""
            case makefile cmakelists.txt; set icon ""
            case readme 'readme.*' license 'license.*' changelog 'changelog.*' agents.md plan.md replit.md; set icon "󰈙"
            case '*.zip' '*.rar' '*.7z' '*.tar' '*.gz' '*.tgz' '*.xz' '*.bz2' '*.zst' '*.iso'; set icon ""
            case '*.sh' '*.bash' '*.zsh' '*.fish' '*.ksh' '*.env' '*.env.*'; set icon ""
            case '*.png' '*.jpg' '*.jpeg' '*.gif' '*.webp' '*.bmp' '*.tiff' '*.ico' '*.svg' '*.avif'; set icon ""
            case '*.mp4' '*.mkv' '*.mov' '*.avi' '*.webm'; set icon ""
            case '*.mp3' '*.wav' '*.flac' '*.ogg' '*.m4a'; set icon "󰝚"
            case '*.py' '*.pyw' '*.ipynb'; set icon ""
            case '*.ts' '*.tsx';       set icon ""
            case '*.js' '*.jsx' '*.mjs' '*.cjs'; set icon ""
            case '*.json' '*.jsonc';   set icon ""
            case '*.go';               set icon ""
            case '*.rs';               set icon ""
            case '*.java' '*.jar' '*.gradle'; set icon ""
            case '*.kt' '*.kts';       set icon ""
            case '*.php';              set icon ""
            case '*.rb' gemfile rakefile; set icon ""
            case '*.lua';              set icon ""
            case '*.c' '*.h';          set icon ""
            case '*.cpp' '*.cc' '*.cxx' '*.hpp' '*.hh' '*.hxx'; set icon ""
            case '*.cs';               set icon "󰌛"
            case '*.swift';            set icon ""
            case '*.dart';             set icon ""
            case '*.vue';              set icon ""
            case '*.svelte';           set icon ""
            case '*.html' '*.htm';     set icon ""
            case '*.css' '*.scss' '*.sass' '*.less'; set icon ""
            case '*.toml';             set icon ""
            case '*.yml' '*.yaml';     set icon ""
            case '*.xml';              set icon "󰗀"
            case '*.md' '*.markdown' '*.mdx'; set icon ""
            case '*.txt' '*.log';      set icon "󰈙"
            case '*.pdf';              set icon ""
            case '*.db' '*.sqlite' '*.sqlite3' '*.sql'; set icon ""
            case '*.ttf' '*.otf' '*.woff' '*.woff2'; set icon ""
            case '*.lock';             set icon ""
            case .replit replit.nix;   set icon ""
        end
    end
    echo "$icon"
end
