# Core prompt. @LEFT@/@RIGHT@ = separators (style file); @PALETTE@ = color file.
add_newline = true
command_timeout = 900
palette = "@PALETTE@"

format = """
[@LEFT@](color_blue)$os$username[](fg:color_blue bg:color_purple)$directory[@RIGHT@ ](fg:color_purple)$git_branch$git_status$c$cpp$rust$golang$nodejs$bun$php$java$kotlin$haskell$python$docker_context$conda$pixi$line_break$character"""

right_format = """$time"""

[os]
disabled = false
style = "bg:color_blue fg:color_bg0"
format = "[ $symbol ]($style)"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Unknown = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
CachyOS = "󰣇"

[username]
show_always = true
style_user = "bg:color_blue fg:color_bg0"
style_root = "bg:color_blue fg:color_bg0"
format = "[$user ]($style)"

[hostname]
ssh_only = true
format = "[@$hostname ]($style)"
style = "bg:color_blue fg:color_bg0"

[time]
disabled = false
time_format = "%R"
style = "fg:color_fg"
format = "[ $time]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[](bold fg:color_green)"
error_symbol = "[](bold fg:color_red)"
vimcmd_symbol = "[](bold fg:color_green)"
vimcmd_replace_one_symbol = "[](bold fg:color_purple)"
vimcmd_replace_symbol = "[](bold fg:color_purple)"
vimcmd_visual_symbol = "[](bold fg:color_yellow)"

[jobs]
symbol = " "
style = "bold color_blue"

[status]
disabled = true
symbol = "✘ "
format = "[$symbol$status]($style) "
style = "bold color_red"

[cmd_duration]
disabled = true
min_time = 1200
format = "[󱎫 $duration]($style) "
style = "color_yellow"
