# Language/tool capsules.
[c]
symbol = ""
format = "[@LEFT@](color_blue)[ $symbol $version ](fg:color_bg0 bg:color_blue)[@RIGHT@ ](fg:color_blue)"

[cpp]
symbol = ""
format = "[@LEFT@](color_blue)[ $symbol $version ](fg:color_bg0 bg:color_blue)[@RIGHT@ ](fg:color_blue)"

[rust]
symbol = ""
format = "[@LEFT@](color_blue)[ $symbol $version ](fg:color_bg0 bg:color_blue)[@RIGHT@ ](fg:color_blue)"

[golang]
symbol = ""
format = "[@LEFT@](color_blue)[ $symbol $version ](fg:color_bg0 bg:color_blue)[@RIGHT@ ](fg:color_blue)"

[nodejs]
symbol = ""
format = "[@LEFT@](color_blue)[ $symbol $version ](fg:color_bg0 bg:color_blue)[@RIGHT@ ](fg:color_blue)"

[bun]
symbol = ""
format = "[@LEFT@](color_blue)[ $symbol $version ](fg:color_bg0 bg:color_blue)[@RIGHT@ ](fg:color_blue)"

[php]
symbol = ""
format = "[@LEFT@](color_blue)[ $symbol $version ](fg:color_bg0 bg:color_blue)[@RIGHT@ ](fg:color_blue)"

[java]
symbol = ""
format = "[@LEFT@](color_blue)[ $symbol $version ](fg:color_bg0 bg:color_blue)[@RIGHT@ ](fg:color_blue)"

[kotlin]
symbol = ""
format = "[@LEFT@](color_blue)[ $symbol $version ](fg:color_bg0 bg:color_blue)[@RIGHT@ ](fg:color_blue)"

[haskell]
symbol = ""
format = "[@LEFT@](color_blue)[ $symbol $version ](fg:color_bg0 bg:color_blue)[@RIGHT@ ](fg:color_blue)"

[python]
symbol = ""
format = "[@LEFT@](color_blue)[ $symbol $version ](fg:color_bg0 bg:color_blue)[@RIGHT@ ](fg:color_blue)"

[docker_context]
symbol = ""
format = "[@LEFT@](color_bg3)[ $symbol $context ](fg:color_sky bg:color_bg3)[@RIGHT@ ](fg:color_bg3)"

[conda]
symbol = ""
format = "[@LEFT@](color_bg3)[ $symbol $environment ](fg:color_sky bg:color_bg3)[@RIGHT@ ](fg:color_bg3)"

[pixi]
symbol = "󰏗"
format = "[@LEFT@](color_bg3)[ $symbol $version $environment ](fg:color_fg bg:color_bg3)[@RIGHT@ ](fg:color_bg3)"
