#!/usr/bin/env fish
# Merge modular Starship sources into ~/.config/starship/starship.toml.
#
# Preference files in this directory:
#   style        — separator style 1-5
#   color        — palette name matching colors/<name>.toml
#   modules.conf — enabled modules, one per line; a leading # disables
#   username     — Fastfetch welcome name
#
# Rebuild by running this file directly, or via:
#   dot-files --edit style|color|modules|username
#
# Uses dotfiles-read-setting / dotfiles-read-modules, autoloaded from
# ~/.config/fish/functions. Missing preference files fall back to defaults.

set -l config_dir (dirname (status --current-filename))
set -l output "$config_dir/starship.toml"
set -l style_file "$config_dir/style"
set -l color_file "$config_dir/color"
set -l modules_file "$config_dir/modules.conf"
set -l colors_dir "$config_dir/colors"
# Env overrides for preview runs (used by dot-files --edit/show-catalog without
# touching the live preference files). When unset, fall back to the preference file.
set -l style
set -l color_theme
if test -n "$STARSHIP_STYLE_PREVIEW"
    set style "$STARSHIP_STYLE_PREVIEW"
else
    set style (dotfiles-read-setting "$style_file"; or echo 5)
end
if test -n "$STARSHIP_COLOR_PREVIEW"
    set color_theme "$STARSHIP_COLOR_PREVIEW"
else
    set color_theme (dotfiles-read-setting "$color_file"; or echo moonlight)
end

set -l selected_color_file "$colors_dir/$color_theme.toml"
if not test -f "$selected_color_file"
    echo "build.fish: unknown color '$color_theme', falling back to moonlight" >&2
    set color_theme moonlight
    set selected_color_file "$colors_dir/moonlight.toml"
end

# Powerline separator glyphs for styles 1-5 (injected into module format strings).
set -l left ''
set -l right ''

switch $style
    case 1
        set left '█'
        set right '█'
    case 2
        set left '░▒▓'
        set right '▓▒░'
    case 3
        set left ''
        set right ''
    case 4
        set left ''
        set right ''
    case 5
        set left ''
        set right ''
    case '*'
        echo "build.fish: unknown style '$style', using 5" >&2
        set style 5
        set left ''
        set right ''
end

set -l left_token '@LEFT@'
set -l right_token '@RIGHT@'
set -l palette_token '@PALETTE@'

echo "# Generated by "(status --current-filename)". Edit modules/*.toml, then run: dot-files --edit modules" > $output
echo "# Active separator style: $style ($left ... $right)" >> $output
echo "# Active color theme: $color_theme" >> $output
echo "# Do not edit this generated file directly unless you know what you are doing." >> $output

set -l enabled_modules (dotfiles-read-modules "$modules_file")
set -l module_order
if test (count $enabled_modules) -gt 0
    # core is mandatory; keep the canonical order, dropping disabled modules.
    if functions -q __dotfiles_all_modules
        set -l all_modules (__dotfiles_all_modules)
    else
        # Fallback when dot-files.fish is not autoloaded (e.g., direct invocation).
        set all_modules core directory git languages package file-icons
    end
    for module_name in $all_modules
        if test "$module_name" = core; or contains -- "$module_name" $enabled_modules
            set -a module_order $module_name
        end
    end
else
    set module_order core directory git languages package file-icons
end

for module_name in $module_order
    set -l module "$config_dir/modules/$module_name.toml"
    if not test -f "$module"
        echo "build.fish: module '$module_name' not found, skipping" >&2
        continue
    end
    echo "" >> $output
    echo "# --- $module_name.toml ---" >> $output
    string replace -a $left_token $left < $module \
        | string replace -a $right_token $right \
        | string replace -a $palette_token $color_theme >> $output
    echo "" >> $output
end

# Palettes must be last: TOML keys after [palettes.*] belong to that table until the next [section].
echo "" >> $output
echo "# --- colors/$color_theme.toml ---" >> $output
cat $selected_color_file >> $output
echo "" >> $output

echo "Built $output with style $style ($left ... $right) and color $color_theme"
