# Catppuccin Macchiato palette.
[palettes.catppuccin-macchiato]
color_fg = "#cad3f5"
color_bg0 = "#181926"
color_bg3 = "#363a4f"
color_blue = "#8aadf4"
color_sky = "#91d7e3"
color_teal = "#8bd5ca"
color_green = "#a6da95"
color_purple = "#c6a0f6"
color_yellow = "#eed49f"
color_red = "#ed8796"
